services:
  # Frontend Service
  - type: web
    name: willmyflightbelate-frontend
    env: static
    buildCommand: |
      cd client
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        value: https://api.willmyflightbelate.com

  # Backend Service
  - type: web
    name: willmyflightbelate-backend
    env: node
    buildCommand: |
      cd server
      npm install --legacy-peer-deps
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: AVIATION_STACK_KEY
        sync: false
      - key: OPENWEATHER_KEY
        sync: false
