services:
  # Static Frontend Service
  - type: static
    name: willmyflightbelate
    buildCommand: cd client && npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./client/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API Service
  - type: web
    name: willmyflightbelate-api
    env: node
    buildCommand: cd server && npm install --legacy-peer-deps
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
