services:
  - type: web
    name: willmyflightbelate
    env: node
    plan: free
    buildCommand: |
      # Debug information
      echo "Current directory: $(pwd)"
      
      # Build frontend
      echo "Building frontend..."
      cd client
      npm install --legacy-peer-deps
      npm run build
      
      # Setup directories and copy files
      echo "Setting up static files..."
      cd ..
      mkdir -p server/public
      cp -rv client/dist/* server/public/
      ls -la server/public
      
      # Build backend
      echo "Building backend..."
      cd server
      npm install --legacy-peer-deps
      
      # Verify files
      echo "Verifying files..."
      ls -la public/
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
