services:
  - type: web
    name: willmyflightbelate
    env: node
    buildCommand: |
      cd client && npm install --legacy-peer-deps && npm run build
      cd ../server && npm install --legacy-peer-deps
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
