services:
  - type: web
    name: willmyflightbelate
    env: node
    buildCommand: |
      echo "Starting build process..."
      echo "Current directory: $(pwd)"
      ls -la
      
      echo "Building frontend..."
      cd client
      echo "Client directory contents:"
      ls -la
      npm install --legacy-peer-deps
      npm run build
      echo "Build output:"
      ls -la dist
      
      echo "Setting up server..."
      cd ../server
      echo "Server directory contents:"
      ls -la
      npm install --legacy-peer-deps
      
      echo "Creating public directory..."
      mkdir -p public
      
      echo "Copying frontend files..."
      cp -rv ../client/dist/* public/
      
      echo "Final directory structure:"
      ls -la
      echo "Public directory contents:"
      ls -la public
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
