services:
  - type: web
    name: willmyflightbelate
    env: node
    buildCommand: |
      # Build frontend
      cd client
      npm install --legacy-peer-deps
      npm run build
      
      # Build backend
      cd ../server
      npm install --legacy-peer-deps
      mkdir -p public
      cp -r ../client/dist/* public/
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
