services:
  - type: web
    name: willmyflightbelate
    env: node
    buildCommand: |
      # Debug start
      echo "Starting build process from $(pwd)"
      
      # Build frontend
      echo "Installing frontend dependencies..."
      cd /opt/render/project/src/client
      npm install --legacy-peer-deps
      
      echo "Building frontend..."
      npm run build
      
      # Build backend
      echo "Installing backend dependencies..."
      cd /opt/render/project/src/server
      npm install --legacy-peer-deps
      
      echo "Creating public directory..."
      mkdir -p /opt/render/project/src/server/public
      
      echo "Copying frontend files..."
      cp -r /opt/render/project/src/client/dist/* /opt/render/project/src/server/public/
      
      echo "Verifying public directory..."
      ls -la /opt/render/project/src/server/public
    startCommand: |
      cd /opt/render/project/src/server
      ls -la public
      node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
