services:
  # Frontend Service
  - type: static
    name: willmyflightbelate-frontend
    buildCommand: |
      cd client
      npm install --legacy-peer-deps
      npm run build
    staticPublishPath: client/dist
    envVars:
      - key: NODE_VERSION
        value: 18.x

  # Backend Service
  - type: web
    name: willmyflightbelate-backend
    env: node
    buildCommand: |
      cd server
      npm install --legacy-peer-deps
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
