services:
  - type: web
    name: willmyflightbelate
    env: node
    plan: free
    buildCommand: |
      # Debug information
      echo "Starting build process..."
      echo "Current directory: $(pwd)"
      
      # Build frontend
      echo "Building frontend..."
      cd client
      npm install --legacy-peer-deps
      npm run build
      echo "Frontend build complete"
      ls -la dist
      
      # Setup directories and copy files
      echo "Setting up static files..."
      cd ..
      rm -rf server/public
      mkdir -p server/public
      echo "Copying files from client/dist to server/public"
      cp -r client/dist/* server/public/ || echo "Error copying files"
      
      # Verify frontend files
      echo "Verifying frontend files..."
      ls -la server/public
      
      # Build backend
      echo "Building backend..."
      cd server
      npm install --legacy-peer-deps
      
      # Final verification
      echo "Final file verification..."
      pwd
      ls -la public/
      if [ ! -f "public/index.html" ]; then
        echo "Error: index.html not found in server/public"
        exit 1
      fi
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
