services:
  - type: web
    name: willmyflightbelate
    env: node
    plan: free
    buildCommand: |
      # Build frontend
      echo "Building frontend..."
      cd client
      npm install --legacy-peer-deps
      npm run build
      
      # Build backend
      echo "Building backend..."
      cd ../server
      npm install --legacy-peer-deps
      
      # Create public directory and copy frontend files
      echo "Copying frontend files..."
      mkdir -p public
      cp -r ../client/dist/* public/
      
      # Verify the copy
      echo "Verifying files..."
      ls -la public/
    startCommand: |
      cd /opt/render/project/src/server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
