services:
  - type: web
    name: flight-delay-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: OPENSKY_USERNAME
        sync: false
      - key: OPENSKY_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    cors:
      allowedOrigins:
        - https://willmyflightbelate.com
        - https://www.willmyflightbelate.com
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      exposedHeaders: []
      maxAge: 86400
      credentials: true
