services:
  - name: flight-delay-predictor
    type: web
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    region: oregon
    envVarsFromSecrets:
      - MONGODB_URI
      - REDIS_URL
      - WEATHERSTACK_KEY
      - AVIATION_STACK_KEY
