services:
  - type: web
    name: willmyflightbelate
    env: node
    buildCommand: |
      # First verify structure
      pwd
      ls -la
      
      # Build frontend
      cd client
      npm install --legacy-peer-deps
      npm run build
      cd ..
      
      # Setup backend
      cd server
      npm install --legacy-peer-deps
      
      # Create public dir and copy files
      rm -rf public
      mkdir -p public
      cp -r ../client/dist/* public/
      ls -la public
    startCommand: cd server && NODE_ENV=production node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
