services:
  # Frontend Service
  - type: web
    name: willmyflightbelate-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_VERSION
        value: 9.x

  # Backend Service
  - type: web
    name: willmyflightbelate-backend
    env: node
    buildCommand: cd server && npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_VERSION
        value: 9.x
