services:
  - type: web
    name: willmyflightbelate
    env: node
    buildCommand: |
      echo "==== Build Starting ===="
      
      # Build frontend
      echo "Building frontend..."
      cd client
      npm install --legacy-peer-deps
      npm run build
      echo "Frontend build complete."
      
      # Setup backend
      cd ../server
      npm install --legacy-peer-deps
      echo "Preparing public directory..."
      rm -rf public
      mkdir -p public
      cp -rv ../client/dist/* public/
      echo "Backend setup complete."
      
      echo "==== Build Complete ===="
    startCommand: |
      echo "==== Starting Server ===="
      cd server
      NODE_ENV=production node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
