services:
  - type: web
    name: willmyflightbelate
    env: node
    buildCommand: |
      # Build the frontend
      cd client
      npm install --legacy-peer-deps
      npm run build

      # Setup the backend
      cd ../server
      npm install --legacy-peer-deps

      # Copy React build to backend's public directory
      mkdir -p public
      cp -rv ../client/build/* public/
    startCommand: |
      # Start the backend server
      cd server
      NODE_ENV=production node index.js
