services:
  # Combined Frontend & Backend Service
  - type: web
    name: willmyflightbelate
    env: node
    plan: free
    buildCommand: |
      # Build frontend
      echo "Building frontend..."
      cd client
      npm install --legacy-peer-deps
      npm run build
      
      # Move the build to public directory
      echo "Setting up static files..."
      mkdir -p ../server/public
      cp -r dist/* ../server/public/
      
      # Build backend
      echo "Building backend..."
      cd ../server
      npm install --legacy-peer-deps
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 18.x
