name: Deploy Flight Delay Predictor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Create env-config.js
      run: |
        echo "window._env_ = {
          OPENSKY_USERNAME: '${{ secrets.OPENSKY_USERNAME }}',
          OPENSKY_PASSWORD: '${{ secrets.OPENSKY_PASSWORD }}'
        };" > public/env-config.js

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
