name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Create env file
        env:
          OPENSKY_USERNAME: ${{ secrets.OPENSKY_USERNAME }}
          OPENSKY_PASSWORD: ${{ secrets.OPENSKY_PASSWORD }}
        run: |
          echo "const env = {" > public/env-config.js
          echo "  OPENSKY_USERNAME: '${{ secrets.OPENSKY_USERNAME }}'," >> public/env-config.js
          echo "  OPENSKY_PASSWORD: '${{ secrets.OPENSKY_PASSWORD }}'" >> public/env-config.js
          echo "};" >> public/env-config.js
          echo "window._env_ = env;" >> public/env-config.js
        
      - name: Build
        run: npm run build
        env:
          CI: false
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
